# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "docker.io/felddy/weewx:latest"
  #amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Weewx"
  org.opencontainers.image.description: "Weex implementation based on weewx-docker"
  org.opencontainers.image.source: "https://github.com/dalethestirling/hassio-addons/weeex"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
