# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:20.0.0"
  # amd64 commented out due to no ability to test
  #amd64: "ghcr.io/hassio-addons/base/amd64:20.0.0"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Weewx"
  org.opencontainers.image.description: "Weex implementation based on weewx-docker"
  org.opencontainers.image.source: "https://github.com/dalethestirling/hassio-addons/weeex"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
